Solving MaxCover for Facebook Budget 100 Depth 150 with train_dist ER_200
Data has been loaded from ../snap_dataset/test/Facebook
Performance of GCNPruner
Size Constraint,k: 100
Size of Ground Set,|U|: 4002
Size of Pruned Ground Set, |Upruned|: 885
Pg(%): 77.89
Ratio: 99.74
C 77.68
Data has been saved to generelization/ER_200/MaxCover/data/Facebook/GNNPruner
**********
Traceback (most recent call last):
  File "/home/grads/a/anath/Pruning_ML/test.py", line 214, in <module>
    game  = env(graph=relabel_subgraph,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MaxCover.__init__() missing 1 required positional argument: 'greedy_rollout_func'
Solving MaxCover for Wiki Budget 100 Depth 150 with train_dist ER_200
Data has been loaded from ../snap_dataset/test/Wiki
Performance of GCNPruner
Size Constraint,k: 100
Size of Ground Set,|U|: 6358
Size of Pruned Ground Set, |Upruned|: 869
Pg(%): 86.33
Ratio: 100.0
C 86.33
Data has been saved to generelization/ER_200/MaxCover/data/Wiki/GNNPruner
**********
Traceback (most recent call last):
  File "/home/grads/a/anath/Pruning_ML/test.py", line 214, in <module>
    game  = env(graph=relabel_subgraph,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MaxCover.__init__() missing 1 required positional argument: 'greedy_rollout_func'
Solving MaxCover for Deezer Budget 100 Depth 150 with train_dist ER_200
Data has been loaded from ../snap_dataset/test/Deezer
Traceback (most recent call last):
  File "/home/grads/a/anath/Pruning_ML/test.py", line 107, in <module>
    pruned_universe_gnn = pruner.test(test_graph)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grads/a/anath/Pruning_ML/gnnpruner_train.py", line 37, in test
    test_data = from_networkx(test_graph)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grads/a/anath/anaconda3/envs/benchenv/lib/python3.11/site-packages/torch_geometric/utils/convert.py", line 235, in from_networkx
    edge_index[1, i] = mapping[dst]
    ~~~~~~~~~~^^^^^^
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/grads/a/anath/Pruning_ML/test_in_series.py", line 37, in <module>
    subprocess.run(cmd, shell=True)
  File "/home/grads/a/anath/anaconda3/envs/benchenv/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grads/a/anath/anaconda3/envs/benchenv/lib/python3.11/subprocess.py", line 1201, in communicate
    self.wait()
  File "/home/grads/a/anath/anaconda3/envs/benchenv/lib/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grads/a/anath/anaconda3/envs/benchenv/lib/python3.11/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/home/grads/a/anath/anaconda3/envs/benchenv/lib/python3.11/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
